github: 
  - ihelloeveryone
  - jpgmv20

patreon: null          # No Patreon account yet
open_collective: null  # No Open Collective account yet
ko_fi: null            # No Ko-fi account yet
tidelift: null         # No Tidelift account yet
community_bridge: null # No Community Bridge project yet
liberapay: null        # No Liberapay account yet
issuehunt: null        # No IssueHunt account yet
lfx_crowdfunding: null # No LFX Crowdfunding project yet
polar: null            # No Polar account yet
buy_me_a_coffee: null  # No Buy Me a Coffee account yet
thanks_dev: null       # No thanks.dev account yet

custom: 
  - "https://discord.gg/xBM7BZmJPH"
